import { BASE, href, pageOf, type Skin } from '../lib/site';

// Static full-text search over the plugin pages. The index is produced by
// Pagefind after the build (src/integrations/pagefind.ts) and loaded lazily on
// first focus, so a visitor who never searches never downloads it.
//
// Only the modern-skin pages are indexed (otherwise every plugin would show up
// twice); result URLs are mapped back onto the skin the visitor is in.

interface PagefindData {
  url: string;
  excerpt: string;
  meta: Record<string, string>;
  filters: Record<string, string[]>;
}
interface PagefindResult {
  id: string;
  data(): Promise<PagefindData>;
}
interface Pagefind {
  options(opts: Record<string, unknown>): Promise<void>;
  search(query: string): Promise<{ results: PagefindResult[] }>;
}

const MAX_RESULTS = 8;
const DEBOUNCE_MS = 120;

const form = document.querySelector<HTMLFormElement>('form[data-search]');
if (form) init(form);

function init(form: HTMLFormElement): void {
  const input = form.querySelector<HTMLInputElement>('input[type="search"]');
  const panel = form.querySelector<HTMLElement>('[data-panel]');
  const list = form.querySelector<HTMLOListElement>('[data-results]');
  const status = form.querySelector<HTMLElement>('[data-status]');
  if (!input || !panel || !list || !status) return;

  const skin = document.documentElement.dataset.skin as Skin;
  let engine: Promise<Pagefind> | null = null;
  let seq = 0;
  let timer: ReturnType<typeof setTimeout> | undefined;

  const load = (): Promise<Pagefind> => {
    engine ??= import(/* @vite-ignore */ `${BASE}pagefind/pagefind.js`).then(
      async (m: Pagefind) => {
        await m.options({ baseUrl: BASE });
        return m;
      },
    );
    return engine;
  };

  const close = (): void => {
    panel.hidden = true;
    input.setAttribute('aria-expanded', 'false');
    list.replaceChildren();
    status.textContent = '';
  };

  const open = (): void => {
    panel.hidden = false;
    input.setAttribute('aria-expanded', 'true');
  };

  const render = (items: PagefindData[], query: string): void => {
    list.replaceChildren(...items.map(resultItem));
    status.textContent = items.length
      ? `${items.length} result${items.length === 1 ? '' : 's'} for “${query}”`
      : `no plugin matches “${query}”`;
    open();
  };

  const resultItem = (d: PagefindData): HTMLLIElement => {
    const li = document.createElement('li');
    const a = document.createElement('a');
    a.href = href(pageOf(d.url), skin);
    const title = document.createElement('span');
    title.className = 's-title';
    title.textContent = d.meta.title ?? pageOf(d.url);
    const cat = document.createElement('span');
    cat.className = 's-cat';
    cat.textContent = d.filters.category?.[0] ?? '';
    const excerpt = document.createElement('span');
    excerpt.className = 's-excerpt';
    // Pagefind escapes page text and only adds <mark>; strip anything else anyway.
    excerpt.innerHTML = d.excerpt.replace(/<(?!\/?mark>)[^>]*>/g, '');
    a.append(title, cat, excerpt);
    li.append(a);
    return li;
  };

  const run = async (): Promise<void> => {
    const query = input.value.trim();
    const mine = ++seq;
    if (!query) {
      close();
      return;
    }
    let pf: Pagefind;
    try {
      pf = await load();
    } catch {
      status.textContent = 'search index missing -- it is generated by `pnpm build`';
      open();
      return;
    }
    const { results } = await pf.search(query);
    if (mine !== seq) return;
    const items = await Promise.all(results.slice(0, MAX_RESULTS).map((r) => r.data()));
    if (mine !== seq) return;
    render(items, query);
  };

  input.addEventListener('focus', () => {
    load().catch(() => {});
  });
  input.addEventListener('input', () => {
    clearTimeout(timer);
    timer = setTimeout(() => void run(), DEBOUNCE_MS);
  });
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    list.querySelector('a')?.click();
  });

  // Keyboard: `/` focuses search anywhere, Esc clears it, arrows walk results.
  const isEditable = (t: EventTarget | null): boolean =>
    t instanceof HTMLElement &&
    (t.isContentEditable || /^(INPUT|TEXTAREA|SELECT)$/.test(t.tagName));

  document.addEventListener('keydown', (e) => {
    if (e.key === '/' && !e.ctrlKey && !e.metaKey && !e.altKey && !isEditable(e.target)) {
      e.preventDefault();
      input.focus();
      input.select();
    }
  });

  form.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') {
      input.value = '';
      close();
      input.blur();
      return;
    }
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp') return;
    const links = [...list.querySelectorAll<HTMLAnchorElement>('a')];
    if (!links.length) return;
    e.preventDefault();
    const i = links.indexOf(document.activeElement as HTMLAnchorElement);
    const next = e.key === 'ArrowDown' ? i + 1 : i - 1;
    if (next < 0) input.focus();
    else links[Math.min(next, links.length - 1)]?.focus();
  });

  document.addEventListener('click', (e) => {
    if (!panel.hidden && e.target instanceof Node && !form.contains(e.target)) close();
  });
}
